# Generated by Django 3.1.6 on 2024-05-09 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireDemandeActeNaissance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('numdoc', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('nombre', models.PositiveIntegerField()),
                ('montant', models.PositiveIntegerField(null=True)),
                ('livraison', models.CharField(max_length=20)),
                ('ville_de_livraison', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu_de_recuperation', models.CharField(blank=True, max_length=50, null=True)),
                ('facture_payee', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
