# Generated by Django 5.0.3 on 2024-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0004_remove_formulairedemandeactenaissance_mairie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="lieu_de_naissance",
            field=models.CharField(max_length=200),
        ),
    ]
