# Generated by Django 5.0.1 on 2024-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0006_formulairedemandeactenaissance_date_commande_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formulairedemandeactenaissance",
            old_name="numdoc",
            new_name="Numéro_CNI",
        ),
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="Numéro_extrait",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="etat_commande",
            field=models.CharField(
                choices=[("actif", "actif"), ("inactif", "inactif")],
                default="Actif",
                max_length=20,
            ),
        ),
    ]
