# Generated by Django 5.0.1 on 2024-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CommanderDoc",
            "0007_rename_numdoc_formulairedemandeactenaissance_numéro_cni_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="formulairedemandeactenaissance",
            old_name="Numéro_CNI",
            new_name="numero_cni",
        ),
        migrations.RemoveField(
            model_name="formulairedemandeactenaissance",
            name="Numéro_extrait",
        ),
        migrations.RemoveField(
            model_name="formulairedemandeactenaissance",
            name="date_commande",
        ),
        migrations.RemoveField(
            model_name="formulairedemandeactenaissance",
            name="user",
        ),
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="numero_extrait",
            field=models.CharField(default="default_extrait", max_length=100),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="lieu_de_naissance",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="lieu_de_recuperation",
            field=models.CharField(default="default_recuperation", max_length=100),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="livraison",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="montant",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="nombre",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="ville_de_livraison",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
