# Generated by Django 5.0.1 on 2024-05-19 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CommanderDoc",
            "0008_rename_numéro_cni_formulairedemandeactenaissance_numero_cni_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="lieu_de_recuperation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="numero_extrait",
            field=models.CharField(max_length=100),
        ),
    ]
