# Generated by Django 5.0.1 on 2024-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0009_formulairedemandeactenaissance_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="nom",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
