# Generated by Django 5.0.1 on 2024-05-19 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0010_alter_formulairedemandeactenaissance_nom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulairedemandeactenaissance",
            name="lieu_de_recuperation",
        ),
        migrations.RemoveField(
            model_name="formulairedemandeactenaissance",
            name="prenom",
        ),
    ]
