# Generated by Django 5.0.1 on 2024-05-20 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CommanderDoc",
            "0011_remove_formulairedemandeactenaissance_lieu_de_recuperation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="date_commande",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
