# Generated by Django 5.0.1 on 2024-05-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0012_formulairedemandeactenaissance_date_commande"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="type_deocument",
            field=models.CharField(default="valeur_par_defaut", max_length=100),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="statut_commande",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("valide", "Validée"),
                    ("refuse", "Refusée"),
                    ("termine", "Terminée"),
                    ("annule", "Annule"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
