# Generated by Django 5.0.1 on 2024-05-20 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0013_formulairedemandeactenaissance_type_deocument_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formulairedemandeactenaissance",
            old_name="type_deocument",
            new_name="type_document",
        ),
    ]
