# Generated by Django 5.0.1 on 2024-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CommanderDoc",
            "0014_rename_type_deocument_formulairedemandeactenaissance_type_document",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="formulairedemandeactenaissance",
            old_name="numero_extrait",
            new_name="numero_Acte",
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="statut_commande",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("valide", "Validée"),
                    ("refuse", "Refusée"),
                    ("termine", "Terminée"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
