# Generated by Django 5.0.1 on 2024-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CommanderDoc",
            "0015_rename_numero_extrait_formulairedemandeactenaissance_numero_acte_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="non_prenom_defunt",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="non_prenom_epouse",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="formulairedemandeactenaissance",
            name="non_prenom_epoux",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="etat_commande",
            field=models.CharField(
                choices=[("actif", "actif"), ("inactif", "inactif")],
                default="actif",
                max_length=20,
            ),
        ),
    ]
