# Generated by Django 5.0.1 on 2024-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0018_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="facture_payee",
            field=models.BooleanField(default=True),
        ),
    ]
