# Generated by Django 5.0.1 on 2024-05-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CommanderDoc",
            "0020_alter_formulairedemandeactenaissance_facture_payee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulairedemandeactenaissance",
            name="lieu_de_naissance",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
