# Generated by Django 5.0.1 on 2024-05-28 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CommanderDoc", "0021_alter_formulairedemandeactenaissance_lieu_de_naissance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulairedemandeactenaissance",
            name="facture_payee",
        ),
    ]
